# Generated by Django 4.2.7 on 2025-10-10 13:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('clock_in_time', models.DateTimeField()),
                ('clock_out_time', models.DateTimeField(blank=True, null=True)),
                ('clock_in_method', models.CharField(choices=[('PORTAL', 'Web Portal'), ('QR_CODE', 'QR Code'), ('API', 'API Integration')], default='PORTAL', max_length=20)),
                ('clock_out_method', models.CharField(blank=True, choices=[('PORTAL', 'Web Portal'), ('QR_CODE', 'QR Code'), ('API', 'API Integration')], max_length=20, null=True)),
                ('status', models.CharField(choices=[('CLOCKED_IN', 'Clocked In'), ('CLOCKED_OUT', 'Clocked Out')], default='CLOCKED_IN', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clock_in_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clock_ins', to='employees.location')),
                ('clock_out_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clock_outs', to='employees.location')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
            ],
            options={
                'ordering': ['-clock_in_time'],
            },
        ),
    ]
