# Generated by Django 4.2.7 on 2025-10-10 16:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Break',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('break_type', models.CharField(choices=[('LUNCH', 'Lunch Break'), ('SHORT', 'Short Break'), ('PERSONAL', 'Personal Break')], max_length=20)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('time_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breaks', to='attendance.timelog')),
            ],
            options={
                'ordering': ['-start_time'],
                'indexes': [models.Index(fields=['time_log', 'start_time'], name='attendance__time_lo_3e7eca_idx'), models.Index(fields=['break_type'], name='attendance__break_t_b7036b_idx')],
            },
        ),
    ]
