# Generated by Django 4.2.7 on 2025-10-10 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_break'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelog',
            name='clock_in_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Clock-in GPS latitude', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='timelog',
            name='clock_in_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Clock-in GPS longitude', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='timelog',
            name='clock_out_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Clock-out GPS latitude', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='timelog',
            name='clock_out_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Clock-out GPS longitude', max_digits=9, null=True),
        ),
    ]
