# Generated by Django 4.2.7 on 2025-10-28 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_add_break_tracking_fields'),
        ('attendance', '0003_timelog_clock_in_latitude_timelog_clock_in_longitude_and_more'),
    ]

    operations = [
    ]
