# Generated by Django 4.2.7 on 2025-10-28 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_merge_20251028_1240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='break',
            name='is_compliant',
        ),
        migrations.RemoveField(
            model_name='break',
            name='reminder_acknowledged',
        ),
        migrations.RemoveField(
            model_name='break',
            name='reminder_acknowledged_at',
        ),
        migrations.RemoveField(
            model_name='break',
            name='waiver_reason',
        ),
        migrations.RemoveField(
            model_name='break',
            name='was_waived',
        ),
        migrations.RemoveField(
            model_name='timelog',
            name='break_reminder_count',
        ),
        migrations.RemoveField(
            model_name='timelog',
            name='break_reminder_sent_at',
        ),
        migrations.RemoveField(
            model_name='timelog',
            name='clock_out_reason',
        ),
    ]
