# Generated by Django 4.2.7 on 2025-10-28 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_remove_break_is_compliant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='break',
            name='is_compliant',
            field=models.BooleanField(default=True, help_text='Meets labor law requirements'),
        ),
        migrations.AddField(
            model_name='break',
            name='reminder_acknowledged',
            field=models.BooleanField(default=False, help_text='Employee acknowledged break reminder'),
        ),
        migrations.AddField(
            model_name='break',
            name='reminder_acknowledged_at',
            field=models.DateTimeField(blank=True, help_text='When break reminder was acknowledged', null=True),
        ),
        migrations.AddField(
            model_name='break',
            name='waiver_reason',
            field=models.TextField(blank=True, help_text='Reason for waiving the break'),
        ),
        migrations.AddField(
            model_name='break',
            name='was_waived',
            field=models.BooleanField(default=False, help_text='Employee waived their break'),
        ),
        migrations.AddField(
            model_name='timelog',
            name='break_reminder_count',
            field=models.IntegerField(default=0, help_text='Number of break reminders sent'),
        ),
        migrations.AddField(
            model_name='timelog',
            name='break_reminder_sent_at',
            field=models.DateTimeField(blank=True, help_text='When break reminder was last sent', null=True),
        ),
        migrations.AddField(
            model_name='timelog',
            name='clock_out_reason',
            field=models.CharField(blank=True, choices=[('END_SHIFT', 'End of Shift'), ('LUNCH_BREAK', 'Lunch Break'), ('SHORT_BREAK', 'Short Break'), ('PERSONAL_BREAK', 'Personal Break'), ('EMERGENCY', 'Emergency'), ('OTHER', 'Other')], help_text='Reason for clocking out', max_length=50, null=True),
        ),
    ]
