# Generated by Django 4.2.7 on 2026-03-10 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_break_is_compliant_break_reminder_acknowledged_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='break',
            name='break_number',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Short Break 1'), (2, 'Long Break'), (3, 'Short Break 2')], help_text='Sequential break slot: 1=Short Break 1, 2=Long Break, 3=Short Break 2', null=True),
        ),
    ]
