# Generated by Django 5.2.7 on 2026-05-14 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_add_break_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='break',
            name='break_type',
            field=models.CharField(choices=[('LUNCH', 'Lunch Break'), ('SHORT', 'Short Break'), ('PERSONAL', 'Personal Break'), ('EMERGENCY', 'Emergency Break')], max_length=20),
        ),
    ]
