# Generated by Django 4.2.7 on 2025-12-26 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_pushsubscription_pushnotificationsettings_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_backend', models.CharField(choices=[('django.core.mail.backends.smtp.EmailBackend', 'SMTP'), ('django.core.mail.backends.console.EmailBackend', 'Console (Development)')], default='django.core.mail.backends.smtp.EmailBackend', max_length=255)),
                ('email_host', models.CharField(help_text='SMTP Host (e.g., smtp.gmail.com)', max_length=255)),
                ('email_port', models.IntegerField(default=587, help_text='SMTP Port (e.g., 587)')),
                ('email_use_tls', models.BooleanField(default=True, help_text='Use TLS')),
                ('email_host_user', models.CharField(help_text='SMTP Username/Email', max_length=255)),
                ('email_host_password', models.CharField(help_text='SMTP Password', max_length=255)),
                ('default_from_email', models.CharField(help_text='Default From Email', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email Configuration',
                'verbose_name_plural': 'Email Configurations',
                'db_table': 'email_configurations',
            },
        ),
    ]
