# Generated by Django 5.2.7 on 2026-04-03 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_emailconfiguration'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regular_rate_multiplier', models.DecimalField(decimal_places=2, default=1.0, help_text='Multiplier for regular hours (≤8h). Default: 1.00', max_digits=4)),
                ('overtime_8_multiplier', models.DecimalField(decimal_places=2, default=1.5, help_text='Multiplier for hours over 8 (up to 12). Default: 1.50', max_digits=4)),
                ('overtime_12_multiplier', models.DecimalField(decimal_places=2, default=2.0, help_text='Multiplier for hours over 12. Default: 2.00', max_digits=4)),
                ('overtime_alert_email', models.EmailField(blank=True, default='', help_text='Email address to receive overtime alerts (e.g., warehouse manager)', max_length=254)),
                ('stuck_clockin_alert_email', models.EmailField(blank=True, default='', help_text='Email address to receive stuck clock-in alerts', max_length=254)),
                ('missed_clockout_hours', models.DecimalField(decimal_places=1, default=2.0, help_text='Hours after shift end to trigger missed clock-out alert', max_digits=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company Settings',
                'verbose_name_plural': 'Company Settings',
                'db_table': 'company_settings',
            },
        ),
    ]
