# Generated by Django 5.2.7 on 2026-04-05 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_companysettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='driver_activity_alert_email',
            field=models.EmailField(blank=True, default='', help_text='Email address to receive Driver clock-in/out and break activity alerts', max_length=254),
        ),
    ]
