# Generated by Django 4.2.7 on 2025-10-14 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('integration_type', models.CharField(choices=[('slack', 'Slack'), ('teams', 'Microsoft Teams'), ('discord', 'Discord'), ('email', 'Email'), ('sms', 'SMS'), ('custom', 'Custom')], max_length=50)),
                ('url_template', models.CharField(blank=True, max_length=500)),
                ('headers_template', models.JSONField(blank=True, default=dict)),
                ('payload_template', models.JSONField(default=dict)),
                ('default_event_types', models.JSONField(default=list)),
                ('default_auth_type', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'webhook_mgmt_templates',
                'ordering': ['integration_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WebhookEndpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('event_types', models.JSONField(default=list, help_text='List of event types to subscribe to')),
                ('secret_key', models.CharField(blank=True, help_text='Secret key for webhook signature', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('FAILED', 'Failed')], default='ACTIVE', max_length=20)),
                ('headers', models.JSONField(blank=True, default=dict, help_text='Additional headers to send')),
                ('auth_type', models.CharField(blank=True, choices=[('', 'None'), ('bearer', 'Bearer Token'), ('basic', 'Basic Auth'), ('api_key', 'API Key')], max_length=50)),
                ('auth_credentials', models.JSONField(blank=True, default=dict, help_text='Authentication credentials')),
                ('max_retries', models.IntegerField(default=3)),
                ('retry_delay', models.IntegerField(default=60, help_text='Delay between retries in seconds')),
                ('timeout', models.IntegerField(default=30, help_text='Request timeout in seconds')),
                ('filter_conditions', models.JSONField(blank=True, default=dict, help_text='Conditions to filter events')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_triggered', models.DateTimeField(blank=True, null=True)),
                ('total_deliveries', models.IntegerField(default=0)),
                ('successful_deliveries', models.IntegerField(default=0)),
                ('failed_deliveries', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_webhooks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'webhook_mgmt_endpoints',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=100)),
                ('resource_type', models.CharField(max_length=50)),
                ('resource_id', models.UUIDField()),
                ('data', models.JSONField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('endpoints_notified', models.IntegerField(default=0)),
                ('successful_deliveries', models.IntegerField(default=0)),
                ('failed_deliveries', models.IntegerField(default=0)),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'webhook_mgmt_events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', 'created_at'], name='webhook_mgm_event_t_5bddb1_idx'), models.Index(fields=['resource_type', 'resource_id'], name='webhook_mgm_resourc_599f06_idx')],
            },
        ),
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=100)),
                ('event_id', models.UUIDField()),
                ('payload', models.JSONField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('RETRYING', 'Retrying')], default='PENDING', max_length=20)),
                ('http_status', models.IntegerField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True)),
                ('response_headers', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('attempt_count', models.IntegerField(default=0)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='webhooks.webhookendpoint')),
            ],
            options={
                'db_table': 'webhook_mgmt_deliveries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['endpoint', 'status'], name='webhook_mgm_endpoin_8cbb94_idx'), models.Index(fields=['event_type', 'created_at'], name='webhook_mgm_event_t_b77d78_idx'), models.Index(fields=['status', 'next_retry_at'], name='webhook_mgm_status_8bf43d_idx')],
            },
        ),
    ]
