# Generated by Django 4.2.7 on 2025-10-23 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_employee_options_alter_location_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='qr_code_payload',
            field=models.CharField(blank=True, help_text='QR code payload for employee identification (auto-generated from employee_id)', max_length=255),
        ),
    ]
