# Generated by Django 4.2.7 on 2025-10-28 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_add_employee_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='qr_enforcement_type',
            field=models.CharField(choices=[('NONE', 'No Enforcement'), ('FIRST_CLOCK_IN', 'First Clock-In Only'), ('ALL_OPERATIONS', 'All Clock-In/Out Operations')], default='NONE', help_text='Level of QR code enforcement for this employee', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='requires_location_qr',
            field=models.BooleanField(default=False, help_text='If True, this employee must use location QR codes for clock-in/out'),
        ),
    ]
