# Generated by Django 4.2.7 on 2025-11-05 09:56

import apps.employees.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_add_qr_enforcement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='hire_date',
            field=models.DateField(default=apps.employees.models.get_current_date),
        ),
    ]
