# Generated by Django 4.2.7 on 2026-04-16 22:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employees', '0005_alter_employee_hire_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='timezone',
            field=models.CharField(default='America/Los_Angeles', help_text="Employee's timezone for shift scheduling and time display", max_length=50),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('EMPLOYEE', 'Employee'), ('DRIVER', 'Driver'), ('SUB_ADMIN', 'Sub Administrator'), ('ADMIN', 'Administrator'), ('SUPER_ADMIN', 'Super Administrator')], max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='SubAdminPermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('permissions', models.JSONField(default=list, help_text="List of permission key strings (e.g. ['view_dashboard', 'manage_schedule'])")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='The admin user who created/last updated this permission set', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sub_admin_permissions', to=settings.AUTH_USER_MODEL)),
                ('employee', models.OneToOneField(help_text='The sub-admin employee this permission set belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='sub_admin_permissions', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Sub-Admin Permission',
                'verbose_name_plural': 'Sub-Admin Permissions',
                'db_table': 'sub_admin_permissions',
            },
        ),
    ]
