# Generated by Django 5.2.7 on 2026-05-15 11:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_alter_employee_timezone_alter_role_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, help_text="Machine-readable action key, e.g. 'edit_employee'", max_length=100)),
                ('category', models.CharField(choices=[('Employees', 'Employees'), ('Time Logs', 'Time Logs'), ('Schedule', 'Schedule'), ('Leave', 'Leave'), ('Locations', 'Locations'), ('Sub-Admins', 'Sub-Admins'), ('Reports', 'Reports'), ('Notifications', 'Notifications'), ('System', 'System')], db_index=True, help_text='Grouping for UI filtering', max_length=50)),
                ('target_type', models.CharField(blank=True, help_text="Class name of the affected model, e.g. 'Employee'", max_length=100)),
                ('target_id', models.CharField(blank=True, help_text='Primary key / UUID of the affected record', max_length=100)),
                ('target_label', models.CharField(blank=True, help_text="Human-readable description of the target, e.g. 'John Doe (EMP-001)'", max_length=255)),
                ('details', models.JSONField(blank=True, default=dict, help_text='Before/after snapshot: {"before": {...}, "after": {...}}')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the request', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(help_text='The user who performed this action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['actor', 'timestamp'], name='audit_logs_actor_i_ce2144_idx'), models.Index(fields=['category', 'timestamp'], name='audit_logs_categor_0633bd_idx'), models.Index(fields=['action', 'timestamp'], name='audit_logs_action_474804_idx')],
            },
        ),
    ]
