# Generated by Django 4.2.7 on 2025-12-03 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporttemplate',
            name='report_type',
            field=models.CharField(choices=[('LATE_ARRIVAL', 'Late Arrival Report'), ('OVERTIME', 'Overtime Report'), ('DEPARTMENT_SUMMARY', 'Department Summary'), ('ATTENDANCE_SUMMARY', 'Attendance Summary'), ('BREAK_COMPLIANCE', 'Break Compliance Report'), ('DETAILED_TIMESHEET', 'Detailed Timesheet'), ('CUSTOM', 'Custom Report')], max_length=20),
        ),
    ]
