# Generated by Django 4.2.7 on 2025-10-10 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_alter_employee_options_alter_location_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Template name (e.g., 'Morning Shift', 'Weekend Coverage')", max_length=100)),
                ('start_time', models.TimeField(help_text='Daily start time')),
                ('end_time', models.TimeField(help_text='Daily end time')),
                ('recurrence_type', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('BIWEEKLY', 'Bi-weekly'), ('MONTHLY', 'Monthly')], default='WEEKLY', max_length=20)),
                ('weekdays', models.JSONField(default=list, help_text='List of weekday numbers (0=Monday, 6=Sunday) for weekly recurrence')),
                ('effective_from', models.DateField(help_text='When this template becomes active')),
                ('effective_until', models.DateField(blank=True, help_text='When this template expires (optional)', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_templates', to='employees.employee')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.location')),
            ],
            options={
                'db_table': 'shift_templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=False, help_text='Whether this shift is published to the employee')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_shifts', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='employees.employee')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.location')),
            ],
            options={
                'db_table': 'shifts',
                'ordering': ['-start_time'],
                'indexes': [models.Index(fields=['employee', 'start_time'], name='shifts_employe_764ff5_idx'), models.Index(fields=['start_time', 'end_time'], name='shifts_start_t_47f534_idx'), models.Index(fields=['is_published'], name='shifts_is_publ_eed893_idx'), models.Index(fields=['location'], name='shifts_locatio_dace9d_idx')],
            },
        ),
    ]
