# Generated by Django 4.2.7 on 2025-10-13 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employees', '0002_alter_employee_options_alter_location_options_and_more'),
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('ANNUAL', 'Annual Leave'), ('SICK', 'Sick Leave'), ('PERSONAL', 'Personal Leave'), ('MATERNITY', 'Maternity Leave'), ('PATERNITY', 'Paternity Leave'), ('BEREAVEMENT', 'Bereavement Leave'), ('STUDY', 'Study Leave'), ('UNPAID', 'Unpaid Leave'), ('COMPENSATORY', 'Compensatory Leave'), ('OTHER', 'Other')], max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_paid', models.BooleanField(default=True)),
                ('requires_approval', models.BooleanField(default=True)),
                ('max_consecutive_days', models.IntegerField(blank=True, help_text='Maximum consecutive days allowed', null=True)),
                ('min_notice_days', models.IntegerField(default=1, help_text='Minimum notice required in days')),
                ('max_advance_days', models.IntegerField(default=365, help_text='Maximum days in advance to request')),
                ('annual_allocation', models.DecimalField(decimal_places=2, default=0, help_text='Annual days allocated', max_digits=5)),
                ('carry_over_allowed', models.BooleanField(default=False)),
                ('max_carry_over_days', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='LeaveApprovalWorkflow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('min_days_threshold', models.DecimalField(decimal_places=2, default=0, help_text='Minimum days to trigger this workflow', max_digits=5)),
                ('max_days_threshold', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum days for this workflow', max_digits=5, null=True)),
                ('requires_all_approvers', models.BooleanField(default=False, help_text='Requires approval from all approvers')),
                ('auto_approve', models.BooleanField(default=False)),
                ('auto_approve_conditions', models.JSONField(blank=True, default=dict, help_text='Conditions for auto-approval')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approvers', models.ManyToManyField(help_text='Users who can approve this type of leave', related_name='leave_approval_workflows', to=settings.AUTH_USER_MODEL)),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_workflows', to='scheduling.leavetype')),
            ],
            options={
                'ordering': ['leave_type', 'min_days_threshold'],
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('days_requested', models.DecimalField(decimal_places=2, max_digits=5)),
                ('reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or comments')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('WITHDRAWN', 'Withdrawn')], default='PENDING', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=100)),
                ('emergency_phone', models.CharField(blank=True, max_length=20)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='leave_attachments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leaves', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='employees.employee')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='scheduling.leavetype')),
            ],
            options={
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['employee', 'status'], name='scheduling__employe_b56e63_idx'), models.Index(fields=['start_date', 'end_date'], name='scheduling__start_d_535a48_idx'), models.Index(fields=['leave_type', 'status'], name='scheduling__leave_t_81534f_idx')],
            },
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.IntegerField(default=2025)),
                ('allocated_days', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('used_days', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('pending_days', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('carried_over_days', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='employees.employee')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='scheduling.leavetype')),
            ],
            options={
                'ordering': ['-year', 'leave_type__display_name'],
                'unique_together': {('employee', 'leave_type', 'year')},
            },
        ),
    ]
