# Generated by Django 4.2.7 on 2025-10-30 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_leavetype_leaveapprovalworkflow_leaverequest_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='shift',
            name='shifts_locatio_dace9d_idx',
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['location'], name='shifts_locatio_83d841_idx'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='location',
            field=models.CharField(blank=True, default='', help_text='Work location (free text)', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shifttemplate',
            name='location',
            field=models.CharField(blank=True, default='', help_text='Work location (free text)', max_length=200),
            preserve_default=False,
        ),
    ]
