# Generated by Django 4.2.7 on 2026-04-16 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0003_rename_shifts_locatio_dace9d_idx_shifts_locatio_83d841_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavebalance',
            name='year',
            field=models.IntegerField(default=2026),
        ),
    ]
