# Generated by Django 5.2.7 on 2026-05-14 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0004_alter_leavebalance_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='shift_type',
            field=models.CharField(choices=[('REGULAR', 'Regular'), ('OVERTIME', 'Overtime'), ('HOLIDAY', 'Holiday'), ('NIGHT', 'Night'), ('DAY_OFF', 'Day Off'), ('SCHEDULED_LEAVE', 'Scheduled Leave'), ('UNSCHEDULED_LEAVE', 'Unscheduled Leave')], default='REGULAR', max_length=20),
        ),
    ]
